version: "3.9"
services:
    mongodb:
        image: mongo:latest
        container_name: mongodb-api
        hostname: mongodb
        ports:
            - "27017:27017"
    phone:
        build: ./phone/.
        ports:
            - 8081:8080
        links:
            - mongodb
    order:
        build: ./order/.
        ports:
            - 8082:8080
        links:
            - phone
            - mongodb
            - user
    user:
        build: ./user/.
        ports:
            - 8083:8080
        links:
            - mongodb
